{% set name = "cfgrib" %}
{% set version = "0.9.15.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d959d8b97e55a63646fa86686b297905ff7f2918a91e3a11d6292dab09598e4d

build:
  number: 0
  skip: true  # [py<310]
  script: bash ${RECIPE_DIR}/build.sh
  entry_points:
    - cfgrib = cfgrib.__main__:cfgrib_cli

requirements:
  host:
    - python
    - pip
    - wheel
    - pytest-runner
    - setuptools
  run:
    - python
    - attrs >=19.2
    - click
    - packaging
    - python-eccodes >=0.9.8
    - numpy
    - xarray >=0.15

test:
  requires:
    - pip
  imports:
    - cf2cdm
    - cfgrib
  commands:
    - pip check
    - cfgrib --help

about:
  home: https://github.com/ecmwf/cfgrib
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Maps GRIB files to the NetCDF Common Data Model with CF Convention using ecCodes
  description: |
    cfgrib is a Python library that provides high-level access to GRIB files via the ECMWF ecCodes
    library. It maps GRIB data to the NetCDF Common Data Model following CF Conventions and can
    serve as an xarray backend engine for reading GRIB files directly into xarray datasets.
  dev_url: https://github.com/ecmwf/cfgrib
  doc_url: https://github.com/ecmwf/cfgrib

extra:
  anaconda-services:
    ref:
      - https://anaconda.zendesk.com/agent/tickets/109074
  recipe-maintainers:
    - amaloney
